import numpy as np
import pickle

import scipy.io as scio

box=scio.loadmat('out_box.mat') # load the regions generated by selective search
index = scio.loadmat('out_index.mat')# the index of image, shows box_list belongs to which image
listBox=[]
listIndex=[]
listScore=[]
# merge into a dictionary
for i in range(len(box['boxes'][0]) ):
    listBox.append(box['boxes'][0][i].astype(np.uint16))# use debug to check the data type from the pkl file from the original method, in WETECTRON it should be float32
    listIndex.append(int(index['indexes'][0][i]))
    listScore.append(np.ones(len(box['boxes'][0][i])).astype(np.float32))# in PCL\CASD\WETECTRON this part is useless and set to be 1
ouput={"boxes":listBox,"indexes":listIndex,"scores":listScore}
# write into pkl file
with open("proposals.pkl", 'wb') as fo:
    pickle.dump(ouput, fo)